<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260923115023 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Monster catalog entity (PvE opponent presets) with bit/ability grants and an uploaded 256x256 icon';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE monster (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(64) NOT NULL,
              description TEXT DEFAULT NULL,
              level INT NOT NULL,
              max_hp INT NOT NULL,
              icon_name VARCHAR(255) DEFAULT NULL,
              icon_size INT DEFAULT NULL,
              icon_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE monster_bit (
              monster_id INT NOT NULL,
              bit_id INT NOT NULL,
              PRIMARY KEY(monster_id, bit_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_9E334564C5FF1223 ON monster_bit (monster_id)');
        $this->addSql('CREATE INDEX IDX_9E3345641D813127 ON monster_bit (bit_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE monster_ability (
              monster_id INT NOT NULL,
              ability_id INT NOT NULL,
              PRIMARY KEY(monster_id, ability_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_97AE5F03C5FF1223 ON monster_ability (monster_id)');
        $this->addSql('CREATE INDEX IDX_97AE5F038016D8B2 ON monster_ability (ability_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster_bit
            ADD
              CONSTRAINT FK_9E334564C5FF1223 FOREIGN KEY (monster_id) REFERENCES monster (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster_bit
            ADD
              CONSTRAINT FK_9E3345641D813127 FOREIGN KEY (bit_id) REFERENCES bit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster_ability
            ADD
              CONSTRAINT FK_97AE5F03C5FF1223 FOREIGN KEY (monster_id) REFERENCES monster (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster_ability
            ADD
              CONSTRAINT FK_97AE5F038016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE monster_bit DROP CONSTRAINT FK_9E334564C5FF1223');
        $this->addSql('ALTER TABLE monster_bit DROP CONSTRAINT FK_9E3345641D813127');
        $this->addSql('ALTER TABLE monster_ability DROP CONSTRAINT FK_97AE5F03C5FF1223');
        $this->addSql('ALTER TABLE monster_ability DROP CONSTRAINT FK_97AE5F038016D8B2');
        $this->addSql('DROP TABLE monster');
        $this->addSql('DROP TABLE monster_bit');
        $this->addSql('DROP TABLE monster_ability');
    }
}
