<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Combat abilities become configurable per class/character/equipment
 * (App\Enum\AbilityType stays the fixed set of 4 kinds; this adds a
 * catalog entity + grant relations so admins can restrict/grant them
 * instead of every ability being available to every class unconditionally).
 *
 * Seeds the 4 fixed ability rows and links every *existing* class to all
 * of them, preserving today's "everything available to everyone" behavior
 * until an admin deliberately restricts something — new classes created
 * afterwards get the same default via SeedCharacterClassesCommand.
 *
 * Uses $this->connection->executeStatement() throughout instead of
 * addSql() — addSql() only queues statements to run after up()/down()
 * returns, which would run the seeding before the tables it depends on
 * even exist.
 */
final class Version20260923113632 extends AbstractMigration
{
    private const ABILITY_TYPES = ['flip', 'unblockable_damage', 'reroll', 'damage_mirror'];

    public function getDescription(): string
    {
        return 'Add Ability catalog + class/character/equipment grants, seeded so every existing class keeps every ability';
    }

    public function up(Schema $schema): void
    {
        $this->connection->executeStatement('CREATE TABLE ability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->connection->executeStatement('CREATE UNIQUE INDEX UNIQ_35CFEE3C8CDE5729 ON ability (type)');
        $this->connection->executeStatement('CREATE TABLE character_ability (character_id INT NOT NULL, ability_id INT NOT NULL, PRIMARY KEY(character_id, ability_id))');
        $this->connection->executeStatement('CREATE INDEX IDX_5C6A6E011136BE75 ON character_ability (character_id)');
        $this->connection->executeStatement('CREATE INDEX IDX_5C6A6E018016D8B2 ON character_ability (ability_id)');
        $this->connection->executeStatement('CREATE TABLE character_class_ability (character_class_id INT NOT NULL, ability_id INT NOT NULL, PRIMARY KEY(character_class_id, ability_id))');
        $this->connection->executeStatement('CREATE INDEX IDX_C40B34B9B201E281 ON character_class_ability (character_class_id)');
        $this->connection->executeStatement('CREATE INDEX IDX_C40B34B98016D8B2 ON character_class_ability (ability_id)');
        $this->connection->executeStatement('ALTER TABLE character_ability ADD CONSTRAINT FK_5C6A6E011136BE75 FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->connection->executeStatement('ALTER TABLE character_ability ADD CONSTRAINT FK_5C6A6E018016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->connection->executeStatement('ALTER TABLE character_class_ability ADD CONSTRAINT FK_C40B34B9B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->connection->executeStatement('ALTER TABLE character_class_ability ADD CONSTRAINT FK_C40B34B98016D8B2 FOREIGN KEY (ability_id) REFERENCES ability (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->connection->executeStatement('ALTER TABLE equipment ADD granted_ability_id INT DEFAULT NULL');
        $this->connection->executeStatement('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583AA83890F FOREIGN KEY (granted_ability_id) REFERENCES ability (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->connection->executeStatement('CREATE INDEX IDX_D338D583AA83890F ON equipment (granted_ability_id)');

        $abilityIds = [];
        foreach (self::ABILITY_TYPES as $type) {
            $abilityIds[] = (int) $this->connection->fetchOne(
                'INSERT INTO ability (type) VALUES (?) RETURNING id',
                [$type],
            );
        }

        $classIds = array_column($this->connection->fetchAllAssociative('SELECT id FROM character_class'), 'id');
        foreach ($classIds as $classId) {
            foreach ($abilityIds as $abilityId) {
                $this->connection->insert('character_class_ability', [
                    'character_class_id' => (int) $classId,
                    'ability_id' => $abilityId,
                ]);
            }
        }
    }

    public function down(Schema $schema): void
    {
        $this->connection->executeStatement('ALTER TABLE character_ability DROP CONSTRAINT FK_5C6A6E011136BE75');
        $this->connection->executeStatement('ALTER TABLE character_ability DROP CONSTRAINT FK_5C6A6E018016D8B2');
        $this->connection->executeStatement('ALTER TABLE character_class_ability DROP CONSTRAINT FK_C40B34B9B201E281');
        $this->connection->executeStatement('ALTER TABLE character_class_ability DROP CONSTRAINT FK_C40B34B98016D8B2');
        $this->connection->executeStatement('DROP TABLE character_ability');
        $this->connection->executeStatement('DROP TABLE character_class_ability');
        $this->connection->executeStatement('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583AA83890F');
        $this->connection->executeStatement('DROP INDEX IDX_D338D583AA83890F');
        $this->connection->executeStatement('ALTER TABLE equipment DROP granted_ability_id');
        $this->connection->executeStatement('DROP TABLE ability');
    }
}
