<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922130321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_quest_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, progress INT NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, character_id INT NOT NULL, quest_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EAB635C61136BE75 ON character_quest_progress (character_id)');
        $this->addSql('CREATE INDEX IDX_EAB635C6209E9EF4 ON character_quest_progress (quest_id)');
        $this->addSql('CREATE TABLE tournament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, champion_character_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD5FB8D9D6859F92 ON tournament (champion_character_id)');
        $this->addSql('CREATE TABLE tournament_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tournament_id INT NOT NULL, character_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EA770D6933D1A3E7 ON tournament_entry (tournament_id)');
        $this->addSql('CREATE INDEX IDX_EA770D691136BE75 ON tournament_entry (character_id)');
        $this->addSql('CREATE TABLE tournament_match (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, round_number INT NOT NULL, slot INT NOT NULL, is_bye BOOLEAN NOT NULL, tournament_id INT NOT NULL, character_a_id INT DEFAULT NULL, character_b_id INT DEFAULT NULL, winner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB0D551C33D1A3E7 ON tournament_match (tournament_id)');
        $this->addSql('CREATE INDEX IDX_BB0D551C2C2247C0 ON tournament_match (character_a_id)');
        $this->addSql('CREATE INDEX IDX_BB0D551C3E97E82E ON tournament_match (character_b_id)');
        $this->addSql('CREATE INDEX IDX_BB0D551C5DFCD4B8 ON tournament_match (winner_id)');
        $this->addSql('CREATE TABLE weekly_quest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_start DATE NOT NULL, type VARCHAR(32) NOT NULL, target_value INT NOT NULL, reward_xp INT NOT NULL, reward_coins INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6525D10754D29C0C ON weekly_quest (week_start)');
        $this->addSql('ALTER TABLE character_quest_progress ADD CONSTRAINT FK_EAB635C61136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_quest_progress ADD CONSTRAINT FK_EAB635C6209E9EF4 FOREIGN KEY (quest_id) REFERENCES weekly_quest (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament ADD CONSTRAINT FK_BD5FB8D9D6859F92 FOREIGN KEY (champion_character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_entry ADD CONSTRAINT FK_EA770D6933D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_entry ADD CONSTRAINT FK_EA770D691136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C33D1A3E7 FOREIGN KEY (tournament_id) REFERENCES tournament (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C2C2247C0 FOREIGN KEY (character_a_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C3E97E82E FOREIGN KEY (character_b_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tournament_match ADD CONSTRAINT FK_BB0D551C5DFCD4B8 FOREIGN KEY (winner_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_quest_progress DROP CONSTRAINT FK_EAB635C61136BE75');
        $this->addSql('ALTER TABLE character_quest_progress DROP CONSTRAINT FK_EAB635C6209E9EF4');
        $this->addSql('ALTER TABLE tournament DROP CONSTRAINT FK_BD5FB8D9D6859F92');
        $this->addSql('ALTER TABLE tournament_entry DROP CONSTRAINT FK_EA770D6933D1A3E7');
        $this->addSql('ALTER TABLE tournament_entry DROP CONSTRAINT FK_EA770D691136BE75');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C33D1A3E7');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C2C2247C0');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C3E97E82E');
        $this->addSql('ALTER TABLE tournament_match DROP CONSTRAINT FK_BB0D551C5DFCD4B8');
        $this->addSql('DROP TABLE character_quest_progress');
        $this->addSql('DROP TABLE tournament');
        $this->addSql('DROP TABLE tournament_entry');
        $this->addSql('DROP TABLE tournament_match');
        $this->addSql('DROP TABLE weekly_quest');
    }
}
