<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922111744 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE battle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, opponent_name VARCHAR(64) NOT NULL, opponent_hp INT NOT NULL, opponent_max_hp INT NOT NULL, status VARCHAR(255) NOT NULL, round_number INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, character_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_139917341136BE75 ON battle (character_id)');
        $this->addSql('CREATE TABLE battle_round (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, round_number INT NOT NULL, player_faces JSON NOT NULL, opponent_faces JSON NOT NULL, damage_to_opponent INT NOT NULL, damage_to_player INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, battle_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DCD5BB86C9732719 ON battle_round (battle_id)');
        $this->addSql('CREATE TABLE bit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, face_a VARCHAR(255) NOT NULL, face_b VARCHAR(255) NOT NULL, character_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5745A3971136BE75 ON bit (character_id)');
        $this->addSql('ALTER TABLE battle ADD CONSTRAINT FK_139917341136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE battle_round ADD CONSTRAINT FK_DCD5BB86C9732719 FOREIGN KEY (battle_id) REFERENCES battle (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bit ADD CONSTRAINT FK_5745A3971136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE battle DROP CONSTRAINT FK_139917341136BE75');
        $this->addSql('ALTER TABLE battle_round DROP CONSTRAINT FK_DCD5BB86C9732719');
        $this->addSql('ALTER TABLE bit DROP CONSTRAINT FK_5745A3971136BE75');
        $this->addSql('DROP TABLE battle');
        $this->addSql('DROP TABLE battle_round');
        $this->addSql('DROP TABLE bit');
    }
}
