<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922125056 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, purchased_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, character_id INT NOT NULL, equipment_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_546877B81136BE75 ON character_equipment (character_id)');
        $this->addSql('CREATE INDEX IDX_546877B8517FE9FE ON character_equipment (equipment_id)');
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, price INT NOT NULL, effect_type VARCHAR(255) NOT NULL, bit_face_a VARCHAR(255) DEFAULT NULL, bit_face_b VARCHAR(255) DEFAULT NULL, hp_bonus INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D338D58377153098 ON equipment (code)');
        $this->addSql('ALTER TABLE character_equipment ADD CONSTRAINT FK_546877B81136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_equipment ADD CONSTRAINT FK_546877B8517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_equipment DROP CONSTRAINT FK_546877B81136BE75');
        $this->addSql('ALTER TABLE character_equipment DROP CONSTRAINT FK_546877B8517FE9FE');
        $this->addSql('DROP TABLE character_equipment');
        $this->addSql('DROP TABLE equipment');
    }
}
