<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Monster loot drops + real character inventory: new Item catalog (weapon/
 * shield/armor/bag = permanent effect while equipped; potion/scroll =
 * instant effect, consumed) and CharacterInventoryItem (one row = one owned
 * item = one inventory cell — see Character::getInventoryCapacity()), plus
 * up to 5 independently-chanced drop slots on Monster (Monster::getDrops(),
 * rolled by LootService on a PvE win).
 */
final class Version20260923181913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Item catalog, CharacterInventoryItem, and Monster drop-table columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE character_inventory_item (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              equipped BOOLEAN NOT NULL,
              acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              character_id INT NOT NULL,
              item_id INT NOT NULL,
              granted_bit_id INT DEFAULT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_7C5092151136BE75 ON character_inventory_item (character_id)');
        $this->addSql('CREATE INDEX IDX_7C509215126F525E ON character_inventory_item (item_id)');
        $this->addSql('CREATE INDEX IDX_7C509215977F4E2A ON character_inventory_item (granted_bit_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE item (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name VARCHAR(64) NOT NULL,
              description TEXT DEFAULT NULL,
              price INT NOT NULL,
              type VARCHAR(255) NOT NULL,
              effect_type VARCHAR(255) NOT NULL,
              bit_face_a VARCHAR(255) DEFAULT NULL,
              bit_face_b VARCHAR(255) DEFAULT NULL,
              bit_advantage_a BOOLEAN NOT NULL,
              bit_advantage_b BOOLEAN NOT NULL,
              bit_multiplier_a INT NOT NULL,
              bit_multiplier_b INT NOT NULL,
              capacity_bonus INT DEFAULT NULL,
              heal_amount INT DEFAULT NULL,
              energy_amount INT DEFAULT NULL,
              xp_amount INT DEFAULT NULL,
              icon_name VARCHAR(255) DEFAULT NULL,
              icon_size INT DEFAULT NULL,
              icon_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              granted_ability_id INT DEFAULT NULL,
              PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_1F1B251EAA83890F ON item (granted_ability_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_inventory_item
            ADD
              CONSTRAINT FK_7C5092151136BE75 FOREIGN KEY (character_id) REFERENCES character (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_inventory_item
            ADD
              CONSTRAINT FK_7C509215126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              character_inventory_item
            ADD
              CONSTRAINT FK_7C509215977F4E2A FOREIGN KEY (granted_bit_id) REFERENCES bit (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              item
            ADD
              CONSTRAINT FK_1F1B251EAA83890F FOREIGN KEY (granted_ability_id) REFERENCES ability (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('ALTER TABLE monster ADD drop_chance1 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_chance2 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_chance3 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_chance4 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_chance5 INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_item1_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_item2_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_item3_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_item4_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE monster ADD drop_item5_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster
            ADD
              CONSTRAINT FK_245EC6F4AE4E61BB FOREIGN KEY (drop_item1_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster
            ADD
              CONSTRAINT FK_245EC6F4BCFBCE55 FOREIGN KEY (drop_item2_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster
            ADD
              CONSTRAINT FK_245EC6F4447A930 FOREIGN KEY (drop_item3_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster
            ADD
              CONSTRAINT FK_245EC6F499909189 FOREIGN KEY (drop_item4_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              monster
            ADD
              CONSTRAINT FK_245EC6F4212CF6EC FOREIGN KEY (drop_item5_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql('CREATE INDEX IDX_245EC6F4AE4E61BB ON monster (drop_item1_id)');
        $this->addSql('CREATE INDEX IDX_245EC6F4BCFBCE55 ON monster (drop_item2_id)');
        $this->addSql('CREATE INDEX IDX_245EC6F4447A930 ON monster (drop_item3_id)');
        $this->addSql('CREATE INDEX IDX_245EC6F499909189 ON monster (drop_item4_id)');
        $this->addSql('CREATE INDEX IDX_245EC6F4212CF6EC ON monster (drop_item5_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE character_inventory_item DROP CONSTRAINT FK_7C5092151136BE75');
        $this->addSql('ALTER TABLE character_inventory_item DROP CONSTRAINT FK_7C509215126F525E');
        $this->addSql('ALTER TABLE character_inventory_item DROP CONSTRAINT FK_7C509215977F4E2A');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EAA83890F');
        $this->addSql('DROP TABLE character_inventory_item');
        $this->addSql('DROP TABLE item');
        $this->addSql('ALTER TABLE monster DROP CONSTRAINT FK_245EC6F4AE4E61BB');
        $this->addSql('ALTER TABLE monster DROP CONSTRAINT FK_245EC6F4BCFBCE55');
        $this->addSql('ALTER TABLE monster DROP CONSTRAINT FK_245EC6F4447A930');
        $this->addSql('ALTER TABLE monster DROP CONSTRAINT FK_245EC6F499909189');
        $this->addSql('ALTER TABLE monster DROP CONSTRAINT FK_245EC6F4212CF6EC');
        $this->addSql('DROP INDEX IDX_245EC6F4AE4E61BB');
        $this->addSql('DROP INDEX IDX_245EC6F4BCFBCE55');
        $this->addSql('DROP INDEX IDX_245EC6F4447A930');
        $this->addSql('DROP INDEX IDX_245EC6F499909189');
        $this->addSql('DROP INDEX IDX_245EC6F4212CF6EC');
        $this->addSql('ALTER TABLE monster DROP drop_chance1');
        $this->addSql('ALTER TABLE monster DROP drop_chance2');
        $this->addSql('ALTER TABLE monster DROP drop_chance3');
        $this->addSql('ALTER TABLE monster DROP drop_chance4');
        $this->addSql('ALTER TABLE monster DROP drop_chance5');
        $this->addSql('ALTER TABLE monster DROP drop_item1_id');
        $this->addSql('ALTER TABLE monster DROP drop_item2_id');
        $this->addSql('ALTER TABLE monster DROP drop_item3_id');
        $this->addSql('ALTER TABLE monster DROP drop_item4_id');
        $this->addSql('ALTER TABLE monster DROP drop_item5_id');
    }
}
