<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922110843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hp INT NOT NULL, max_hp INT NOT NULL, energy INT NOT NULL, max_energy INT NOT NULL, level INT NOT NULL, xp INT NOT NULL, coins INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_937AB034A76ED395 ON character (user_id)');
        $this->addSql('CREATE INDEX IDX_937AB034B201E281 ON character (character_class_id)');
        $this->addSql('CREATE TABLE character_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, description TEXT DEFAULT NULL, base_hp INT NOT NULL, base_energy INT NOT NULL, starter_bits JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1388FEFD77153098 ON character_class (code)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, discord_id VARCHAR(32) NOT NULL, username VARCHAR(64) NOT NULL, avatar VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64943349DE ON "user" (discord_id)');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB034A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB034B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034A76ED395');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB034B201E281');
        $this->addSql('DROP TABLE character');
        $this->addSql('DROP TABLE character_class');
        $this->addSql('DROP TABLE "user"');
    }
}
